// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Solutions from "./Solutions.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(Solutions.make, {}),
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Solutions Not a pure module */
