// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "../Common.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import Ca9ddb6Json from "../data/training/0ca9ddb6.json";

var taskName = "0ca9ddb6";

var data = Ca9ddb6Json;

function main(input) {
  var redFlower = Core__Array.reduce(Common.getCoordsOfColors(input, ["Red"]), input, (function (acc, cur) {
          return Common.adjustRel(Common.adjustRel(Common.adjustRel(Common.adjustRel(acc, (function (param) {
                                    return "Yellow";
                                  }), [
                                  cur.x + 1 | 0,
                                  cur.y + 1 | 0
                                ], [
                                  0,
                                  0
                                ]), (function (param) {
                                return "Yellow";
                              }), [
                              cur.x - 1 | 0,
                              cur.y + 1 | 0
                            ], [
                              0,
                              0
                            ]), (function (param) {
                            return "Yellow";
                          }), [
                          cur.x + 1 | 0,
                          cur.y - 1 | 0
                        ], [
                          0,
                          0
                        ]), (function (param) {
                        return "Yellow";
                      }), [
                      cur.x - 1 | 0,
                      cur.y - 1 | 0
                    ], [
                      0,
                      0
                    ]);
        }));
  return Core__Array.reduce(Common.getCoordsOfColors(redFlower, ["Blue"]), redFlower, (function (acc, cur) {
                return Common.adjustRel(Common.adjustRel(Common.adjustRel(Common.adjustRel(acc, (function (param) {
                                          return "Orange";
                                        }), [
                                        cur.x + 1 | 0,
                                        cur.y
                                      ], [
                                        0,
                                        0
                                      ]), (function (param) {
                                      return "Orange";
                                    }), [
                                    cur.x - 1 | 0,
                                    cur.y
                                  ], [
                                    0,
                                    0
                                  ]), (function (param) {
                                  return "Orange";
                                }), [
                                cur.x,
                                cur.y + 1 | 0
                              ], [
                                0,
                                0
                              ]), (function (param) {
                              return "Orange";
                            }), [
                            cur.x,
                            cur.y - 1 | 0
                          ], [
                            0,
                            0
                          ]);
              }));
}

var solutionExport = {
  taskName: taskName,
  data: data,
  main: main
};

export {
  taskName ,
  data ,
  main ,
  solutionExport ,
}
/* data Not a pure module */
