// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "../Common.res.mjs";

var taskName = "0d3d703e";

var data = {
  train: [
    {
      input: [
        [
          3,
          1,
          2
        ],
        [
          3,
          1,
          2
        ],
        [
          3,
          1,
          2
        ]
      ],
      output: [
        [
          4,
          5,
          6
        ],
        [
          4,
          5,
          6
        ],
        [
          4,
          5,
          6
        ]
      ]
    },
    {
      input: [
        [
          2,
          3,
          8
        ],
        [
          2,
          3,
          8
        ],
        [
          2,
          3,
          8
        ]
      ],
      output: [
        [
          6,
          4,
          9
        ],
        [
          6,
          4,
          9
        ],
        [
          6,
          4,
          9
        ]
      ]
    },
    {
      input: [
        [
          5,
          8,
          6
        ],
        [
          5,
          8,
          6
        ],
        [
          5,
          8,
          6
        ]
      ],
      output: [
        [
          1,
          9,
          2
        ],
        [
          1,
          9,
          2
        ],
        [
          1,
          9,
          2
        ]
      ]
    },
    {
      input: [
        [
          9,
          4,
          2
        ],
        [
          9,
          4,
          2
        ],
        [
          9,
          4,
          2
        ]
      ],
      output: [
        [
          8,
          3,
          6
        ],
        [
          8,
          3,
          6
        ],
        [
          8,
          3,
          6
        ]
      ]
    }
  ],
  test: [{
      input: [
        [
          8,
          1,
          3
        ],
        [
          8,
          1,
          3
        ],
        [
          8,
          1,
          3
        ]
      ],
      output: [
        [
          9,
          5,
          4
        ],
        [
          9,
          5,
          4
        ],
        [
          9,
          5,
          4
        ]
      ]
    }]
};

function newColor(color) {
  switch (color) {
    case "Black" :
        return "Orange";
    case "Blue" :
        return "Gray";
    case "Red" :
        return "Pink";
    case "Green" :
        return "Yellow";
    case "Yellow" :
        return "Green";
    case "Gray" :
        return "Blue";
    case "Pink" :
        return "Red";
    case "Orange" :
        return "Black";
    case "Cyan" :
        return "Brown";
    case "Brown" :
        return "Cyan";
    
  }
}

var tests = Common.allTests(data);

function main(input) {
  return Common.adjustAll(input, (function (color, param, param$1) {
                return newColor(color);
              }));
}

var solutionExport = {
  taskName: taskName,
  tests: tests,
  main: main
};

export {
  taskName ,
  data ,
  newColor ,
  tests ,
  main ,
  solutionExport ,
}
/* tests Not a pure module */
