// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "../Common.res.mjs";
import D3d703eJson from "../data/training/0d3d703e.json";

var taskName = "0d3d703e";

var data = D3d703eJson;

function newColor(color) {
  switch (color) {
    case "Black" :
        return "Orange";
    case "Blue" :
        return "Gray";
    case "Red" :
        return "Pink";
    case "Green" :
        return "Yellow";
    case "Yellow" :
        return "Green";
    case "Gray" :
        return "Blue";
    case "Pink" :
        return "Red";
    case "Orange" :
        return "Black";
    case "Cyan" :
        return "Brown";
    case "Brown" :
        return "Cyan";
    
  }
}

var tests = Common.allTests(data);

function main(input) {
  return Common.adjustAll(input, (function (color, param, param$1) {
                return newColor(color);
              }));
}

var solutionExport = {
  taskName: taskName,
  data: data,
  main: main
};

export {
  taskName ,
  data ,
  newColor ,
  tests ,
  main ,
  solutionExport ,
}
/* data Not a pure module */
