// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "../Common.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import Aa6fb7aJson from "../data/training/3aa6fb7a.json";

var taskName = "3aa6fb7a";

var data = Aa6fb7aJson;

function insideCorner(corner) {
  switch (corner.TAG) {
    case "TL" :
        var c = corner._0;
        return [
                c.x + 1 | 0,
                c.y + 1 | 0
              ];
    case "TR" :
        var c$1 = corner._0;
        return [
                c$1.x - 1 | 0,
                c$1.y + 1 | 0
              ];
    case "BL" :
        var c$2 = corner._0;
        return [
                c$2.x + 1 | 0,
                c$2.y - 1 | 0
              ];
    case "BR" :
        var c$3 = corner._0;
        return [
                c$3.x - 1 | 0,
                c$3.y - 1 | 0
              ];
    
  }
}

function main(input) {
  return Core__Array.reduce(Common.getCorners(Common.getCoordsOfColors(input, ["Cyan"])), input, (function (acc, cur) {
                return Common.adjustRel(acc, (function (param) {
                              return "Blue";
                            }), insideCorner(cur), [
                            0,
                            0
                          ]);
              }));
}

var solutionExport = {
  taskName: taskName,
  data: data,
  main: main
};

export {
  taskName ,
  data ,
  insideCorner ,
  main ,
  solutionExport ,
}
/* data Not a pure module */
