// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "../Common.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import B148d64Json from "../data/training/0b148d64.json";

var taskName = "0b148d64";

var data = B148d64Json;

function main(input) {
  var blackRows = Common.findLinesOfColor(input, "Black");
  var blackColumns = Common.findLinesOfColor(Common.transpose(input), "Black");
  var match = Common.maxes(input);
  var blockSpecs = Common.getBlockSpecs(Common.converses(blackRows, match[0]), Common.converses(blackColumns, match[1]));
  var blocks = Common.carve(input, blockSpecs);
  return Core__Option.flatMap(Belt_MapString.findFirstBy(Common.colorCount(Belt_Array.keepMap(Common.blocksNonBlackColor(blocks), (function (param) {
                            return param[1];
                          }))), (function (_k, v) {
                    return v === 1;
                  })), (function (param) {
                var k = param[0];
                return Core__Option.map(Common.blocksNonBlackColor(blocks).find(function (param) {
                                return Core__Option.mapOr(param[1], false, (function (c) {
                                              return Common.colorToString(c) === k;
                                            }));
                              }), (function (param) {
                              return param[0];
                            }));
              }));
}

var solutionExport = {
  taskName: taskName,
  data: data,
  main: main
};

export {
  taskName ,
  data ,
  main ,
  solutionExport ,
}
/* data Not a pure module */
