// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "../Common.res.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import Fde7Json from "../data/training/0520fde7.json";

var taskName = "0520fde7";

var data = Fde7Json;

function main(input) {
  var superimposedBlues = Common.getCoordsOfColors(input, ["Blue"]).map(function (c) {
        if (c.y > 3) {
          return {
                  x: c.x,
                  y: c.y - 4 | 0,
                  color: c.color
                };
        } else {
          return c;
        }
      });
  var doubleBlues = superimposedBlues.filter(function (c) {
        return superimposedBlues.filter(function (c2) {
                    if (c2.x === c.x) {
                      return c2.y === c.y;
                    } else {
                      return false;
                    }
                  }).length > 1;
      });
  return Core__Array.reduce(doubleBlues, Common.blank("Black", 2, 2), (function (acc, cur) {
                return Common.adjustRel(acc, (function (param) {
                              return "Red";
                            }), [
                            cur.x,
                            cur.y
                          ], [
                            0,
                            0
                          ]);
              }));
}

var solutionExport = {
  taskName: taskName,
  data: data,
  main: main
};

export {
  taskName ,
  data ,
  main ,
  solutionExport ,
}
/* data Not a pure module */
